---
name: "Release"

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: install toolchain
        run: sudo apt -y install gcc-arm-none-eabi
      - name: check toolchain
        run: arm-none-eabi-gcc --version
      - name: build varmint
        run: mkdir build && cd build && cmake .. -DBUILD_VARMINT=true && make

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/varmint.hex
